### ISSUE TITLE
List items are not dragable anymore if the number of lists has become 0

### ISSUE THREAD

**Issue by Mortivarus** [apankrat/nullboard#41] opened 2021-04-14 13:10 UTC
If the amount if lists has become zero (e.g. if you add a new board) and then add lists with items again, the items are no longer dragable between lists.

**Comment by apankrat** [comment] 2021-04-14 13:55
Can't reproduce this. More specifically - I added a new board, then added a new list, then added a note, then added two more using Ctrl-Enter, ending editing with Alt-Enter. Notes are draggable as expected. I will need to know browser brand/version and the exact list of steps that trigger this behavior.

**Comment by apankrat** [comment] 2021-04-14 13:55
Ah, nevermind. I can't indeed drag notes _between_ the lists.

**Comment by apankrat** [comment] 2021-04-14 14:29
Fixed with b630ef618d0 and pushed to https://nullboard.io/preview. Thanks for the report @Mortivarus.

**Closed by apankrat** 2021-04-14 14:29 UTC
